apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
      - name: simple-server
        image: docker.io/library/simple-python-service:latest
        imagePullPolicy: Never
        env:
          - name: SERVICE_RESPONSE
            value: "Version 1"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "128Mi"
